events { worker_connections 1024; }

http {
    upstream rate_limiter_cluster {
        server rate_limiter_1:8000;
        server rate_limiter_2:8000;
        server rate_limiter_3:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://rate_limiter_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}