events { worker_connections 1024; }

http {
    # Define the cluster of backend applications
    upstream backend_cluster {
        server web_app_1:8000;
        server web_app_2:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}